### ISSUE TITLE
Android client plan

### ISSUE THREAD

**Issue by simpleblack** [8enmann/WebtendoClient#1]
I tested android client.

And I had error
https://github.com/oney/react-native-webrtc/issues/343
I have solved but connect fail occurs often for android. not error.
Sometime connect success.

When do you plan to make android client?

**Comment by 8enmann** [comment]
Android client? Using Chrome doesn't work? How did you test?

**Comment by simpleblack** [comment]
Not used chrome. not used webview.

only react-naitve and Installed react-native-webrtc test.
But I had error to webrtc.
I guess problem `IceCandidate`.

This repo `README`. I see todo list first `Android client`.
You don't have plan?

**Comment by 8enmann** [comment]
No plan since the web client appears to work fine. See https://github.com/8enmann/Webtendo

**Comment by simpleblack** [comment]
Thanks
